// Generated by https://quicktype.io

export interface GuildCommand {
    id:                 string;
    application_id:     string;
    name:               string;
    description:        string;
    version:            string;
    default_permission: boolean;
    guild_id:           string;
    options?:           Option[];
}

export interface Option {
    type:        number;
    name:        string;
    description: string;
    options?:    Option[];
    required?:   boolean;
}
